### ISSUE TITLE
micro:bit v1.3B: program cannot be modified

### ISSUE THREAD

**Issue by PSLLSP** [veryalien/mycobit#3]
micro:bit v1.3B was flash with prepared [HEX file mycobit.hex](https://github.com/veryalien/mycobit/blob/master/mycobit.hex). It looks like it works OK, I see LED pattern, dot falls down again and again, I call it rain pattern.

First. I note that program flashed in the micro:bit is different from program in the description and it works! This is the default program:

` 43 52 43 53 41 54 7B 25 B5 10 60 71 50 A2 3E`

My Micro:bit has this code (7B is replaced with 70):

`43 52 43 53 41 54 70 25 B5 10 60 71 50 A2 3E`

Instruction `0x70` is not defined, `0x7B` is `A<<1`. But it works! I tried to fix it but program is reverted to "buggy" version, to code `0x70`, like the change is not saved, I cannot change 0x70 to 0x7B!

Second. I tried to code simple demo from the original CONRAD kit [EAN 9783645101042](https://www.conrad.de/de/p/conrad-components-10104-profi-mikrocontroller-elektronik-lernpaket-ab-14-jahre-192286.html) to blink LEDs; code is `11 28 18 28 34` but it was not saved, after reset I see "rain pattern" again.

It is serious issue because, from my point of view, such micro:bit cannot be used in any useful way...

---

UPDATE. I can save my program. **mycobit** is different from the original CONRAD kit in the way that I have to do an extra action to save the code. I missed that. I tried instructions to code `1A 30` and it works, I see new pattern. 

I was able to fix the demo code, to replace 0x70 with 0x7B and I see different pattern now, I see 16 LEDS are used.

The last question that remains is what is code 0x70, it looks like it is A<<4.

I assume that I modified 0x7B to 0x70 when I learned how to use mycobit, that was a lucky accident because I was able to save the code that is tricky on mycobit. Original CONRAD kit has a sequence to load default code, program code `FF FF` and after reset, the FLASH is initiated to the default state.

Other issue I see is that default code is different from the original "TPS", it means that original documentation cannot be used to learn how to program this cool toy... :-( It is a lot of work to code all 128 bytes to have all subroutines in the FLASH like original "TPS" have...

---

UPDATE: Reset with `FF FF` code works, it copies code with all subroutines, etc, after this *destructive* action, original tutorial for "TPS" can be used to learn how to code this toy. GREAT! The key information is that `FF FF` has to be saved to FLASH with an extra action (press B+A, in this sequence).

---

I close this issue, it was just an human error based on my experience with the original TPS....

**Comment by PSLLSP** [comment]
human error.. ;-)

**Comment by veryalien** [comment]
I assume I can close this issue, or do you still have a problem?
